### ISSUE TITLE
Illumos: collecting entropy via /dev/urandom failed.

### ISSUE THREAD

**Issue by hoper-a11y** [jrmarino/ravensw#4]
To be clear, this issue is of the pkg shipped with raven sunos bootstrap, not this reimplementation and the Illumos used is OpenIndiana. Other than that, pkg worked very well on this platform.

I know reporting here is wrong, but I don't know where is the right place to report this issue at all.

**Comment by jrmarino** [comment]
wait, the sunos bootstrap still has "pkg" and not "ravensw" ?

**Comment by hoper-a11y** [comment]
> wait, the sunos bootstrap still has "pkg" and not "ravensw" ?

What? So you already replaced pkg with ravensw on sunos?

I don't know about this. I think ravensw is currently not in usable state since I didn't see you make any releases for it. So because this misinformation I have created a mess?

Sorry you very much. Sometimes I found I'm too passionate and caused many troubles for the projects I want to contribute.

**Comment by jrmarino** [comment]
there are 2 versions of ravensw.
The first is a renamed pkg(8).  It's just pkg, but renamed to ravensw, mainly to avoid conflict with openindiana's pkg tool.
the second is the reimplementation which is not done yet.  I'm referring to the C version.

**Comment by jrmarino** [comment]
so if you are using "pkg" for ravenports, it's really old.  It should be "ravensw".  And it should be with a "_6" revision.

**Comment by hoper-a11y** [comment]
> there are 2 versions of ravensw.
> The first is a renamed pkg(8). It's just pkg, but renamed to ravensw, mainly to avoid conflict with openindiana's pkg tool.
> the second is the reimplementation which is not done yet. I'm referring to the C version.

Now I'm really confused. So what is pkg-static? I used pkg-static to avoid conflict with system's pkg. This pkg-static give the /dev/urandom warning. BTW, your quickstart guide still uses pkg and pkg-static, not ravensw.

**Comment by jrmarino** [comment]
I guess the sun guide wasn't updated.
pkg-static is gone.
Read the dragonfly/freebsd guide to see differences.
Feel free to update the wiki if you can't wait for me to do.
But if pkg-static is still in sun bootstrap, that's a problem.  You might have an old bootstrap.

**Comment by kraileth** [comment]
@jrmarino To me it seems that the sunos bootstrap package wasn't updated. I was quite sure that it still contained pkg last time I needed it and just checked: http://www.ravenports.com/repository/raven-sunos-bootstrap.tar.gz is from Dec. 2019 according to the web server, but if you extract it, contains pkg from Jul 2018. Are you sure that the correct bootstrap package is available? I wondered about this before but thought that ravensw simply wasn't ready for Solaris, yet.

**Comment by jrmarino** [comment]
Well, that seems like an oversight.  The bootstrap package has to be rebuilt and the quickstart guide updated then.

**Comment by hoper-a11y** [comment]
> I guess the sun guide wasn't updated.
> pkg-static is gone.
> Read the dragonfly/freebsd guide to see differences.
> Feel free to update the wiki if you can't wait for me to do.
> But if pkg-static is still in sun bootstrap, that's a problem. You might have an old bootstrap.

Both the sun and linux bootstrap are not updated. The same as what on 2018.
Yes, I have read the quickstart of freebsd and dfbsd. They are updated.

**Comment by hoper-a11y** [comment]
> @jrmarino To me it seems that the sunos bootstrap package wasn't updated. I was quite sure that it still contained pkg last time I needed it and just checked: http://www.ravenports.com/repository/raven-sunos-bootstrap.tar.gz is from Dec. 2019 according to the web server, but if you extract it, contains pkg from Jul 2018. Are you sure that the correct bootstrap package is available? I wondered about this before but thought that ravensw simply wasn't ready for Solaris, yet.

I think due to his work on freebsd and dfbsd, he could keep the guides for them more up to date. The linux and sun targets are pretty much minor targets. I think when he got everything right on freebsd and dfbsd, he would revisit the minor targets. But now, don't expect anything.

**Comment by hoper-a11y** [comment]
> Well, that seems like an oversight. The bootstrap package has to be rebuilt and the quickstart guide updated then.

I'm waiting to test your new bootstrap. But I admit I'm pretty much lost my interest on ravenports on linux so it could be the last time I test it on linux. I'm more concerned about the sun ravenports now.

**Comment by kraileth** [comment]
@hoper-a11y There's no such thing as a minor target in RP. The problem  is simply that most people using Ravenports right now come from a *BSD background which is why those platforms are in a bit better shape. As you've seen here regarding Solaris/illumos we're explicitly welcoming folks from those platforms who bring in their knowledge and better understanding. Same thing for Linux. My bet would be that if somebody from another OS - say Haiku for example which is at least partly POSIXy - came by and offered to port RP to that, he probably wouldn't be turned down if he's serious about the matter.

It might help to consider RP as a kind of a "public demo" on those platforms until somebody whose primary platform is Solaris/Linux joins in. Until that happens support is a "best effort" kind of thing. Both the Sun-derived and Linux platforms are equally important, but they are not operating systems that we're extremely familiar with. In fact even on DF/FreeBSD RP is currently an "early adopters" project meant for testing. It works pretty well for what the developers need it for (and has done so for quite some time already), but it's still a young project.

So for my part I'm happy that you came along, but both illumos and Linux need more time to mature. The biggest issue right now is ravensw stability. But that's being worked on actively, so I'd expect that RP will be actually usable on Linux a bit later this year.

**Comment by hoper-a11y** [comment]
It seemed the this bug is finally gone with the latest version of ravensw.

**Comment by jrmarino** [comment]
I've updated the bootstrap and the text in the quickstart guide.
I'm going to rebuild all the packages.  That will take some hours.
It will *not* fix the reported compiler/linker issue.  That's going to take some time to think about the best approach.

**Comment by jrmarino** [comment]
The bootstrap contains ravensw 1.11_6, the latest.

**Comment by hoper-a11y** [comment]
> I've updated the bootstrap and the text in the quickstart guide.
> I'm going to rebuild all the packages. That will take some hours.
> It will _not_ fix the reported compiler/linker issue. That's going to take some time to think about the best approach.

I unsubscribed from this issue so I didn't see your comment. Updated to the latest bootstrap and ravensw is very stable now. The /dev/urandom problem is completely gone so I think it's reasonable to close this issue.

**Comment by jrmarino** [comment]
It's nice to know /dev/urandom issue seems to be gone.
All the rebuilt packages are available now.
I'm going to work on fixing the gnu compilers.
