### ISSUE TITLE
Reconsider re-implement of FreeBSD's pkg using Ada

### ISSUE THREAD

**Issue by hoper-a11y** [jrmarino/ravensw#5]
No, the title is a bit misleading. I don't want to discourage you from doing so at all. Indeed, I think it's the right direction in the long run. We should divert ourselves as far as possible from FreeBSD's pkg to the state that the only common thing between we and them is the pkg's package format.

I know pkg in general is a bad quality tool (in the stability and portability regards, though, because most of the time pkg done the job well on it native platforms which is FreeBSD and DragonflyBSD). But it seemed most of the problem with pkg is on the Linux platform, also the biggest market for ravenports.

Why I said so? Did I used to bash pkg very much? No, I didn't bash pkg, I just said what I have experienced. I said so because my experience with pkg on OpenIndiana. Apart from the warning "Collection entropy via /dev/urandom failed.", in general, it's pretty stable and done the job well. I didn't get any segmentation faults or crashes at all, compared to Linux that it just crashed when attempted to install a very small package which is wget-complete-standard.

All of this, caused me to reconsider the problem. And my conclusion is it's because of the way we distribute ravenports on Linux.

Linux's glibc is not have good compatible between versions despite they said it's so. So distributing precompiled bootstrap caused every trouble we encountered with.

Instead, I think you should reconsider to distribute ravenports, at least only on Linux, via source bootstrapping like what pkgsrc currently does. You don't provide the precompiled bootstrap anymore, the users have to bootstrap their own ravenports from source. This will eliminate any problems with glibc's incompatibility.

Addition to that, I think you should only provide prebuilt binary for Enterprise Linux like what Joyent currently does. They only provide packages for EL6 and EL7. If people took these packages and install it on different distros, for example, Debian, it just doesn't work at all. So I suggest only provide prebuilt packages for Enterpise Linux, on other distros, ravenports remains as a ports system, where the users have to compile everything from source themselves.

This is just my sincere words because I really want to see ravenports to success. Please consider all of this. Thanks.

**Comment by jrmarino** [comment]
IIRC pkg is dynamically linked to glibc so there shouldn't be anything with with a precompiled binary.
we've got other issues -- naming the abi.  sometimes it's 2.6.32, sometimes its 3.2.x.   Once I get ravensw redone I can concentrate on linux and solaris.

**Comment by jrmarino** [comment]
and nothing prevents people from building their own repositories ... as long as the "ravenports" meta package and it's dependencies work.

**Comment by hoper-a11y** [comment]
> IIRC pkg is dynamically linked to glibc so there shouldn't be anything with with a precompiled binary.
> we've got other issues -- naming the abi. sometimes it's 2.6.32, sometimes its 3.2.x. Once I get ravensw redone I can concentrate on linux and solaris.

Pardon my ignorant but if it's just two abi why don't just create two bootstrap versions?

BTW, I accidentally closed my issue about /dev/urandom. If you already replaced pkg with ravensw on sunos then it's ravensw's bug on openindiana. I don't know if this bug is serious or not but pkg (or ravensw indeed) worked fine on oi.

**Comment by hoper-a11y** [comment]
> and nothing prevents people from building their own repositories ... as long as the "ravenports" meta package and it's dependencies work.

Sometimes I want to use prebuilt packages from you. Mostly when to install monster packages like LLVM that can't even build on my system at all (doesn't have enough resource) or packages that took too much time to build. I don't know why but I could build GCC normally, but I never possible to build LLVM on my system.

**Comment by hoper-a11y** [comment]
BTW, about the abi problem. I don't think it's the case. Because I have seen software built for abi 2.4.0 still run happily on my abi 3.2.0 system. The most notable is software built by freepascal and lazarus.

**Comment by jrmarino** [comment]
I haven't investigated all the consequences.  Theoretically there should be none.  The reported issues were probably pkg issues, not the packages themselves.  So maybe the abi is not an issue at all.
and repeating here: the ravensw we talk about is the C version.  The rewrite in ada isn't available yet.

**Comment by hoper-a11y** [comment]
> I haven't investigated all the consequences. Theoretically there should be none. The reported issues were probably pkg issues, not the packages themselves. So maybe the abi is not an issue at all.
> and repeating here: the ravensw we talk about is the C version. The rewrite in ada isn't available yet.

Could you setup a Debian Buster VM and compiled the your bootstrap natively there then check if pkg still have problems with check integrity? From my experience I still think it's because you compiled your bootstrap on another distro so when I use it on my Debian it's unstable because of the incompatibility between the two system.

BTW, why don't you offer us the ability to compile the bootstrap from source ourselves? Currently you only provide prebuilt binary.

**Comment by jrmarino** [comment]
because it takes an expert to bootstrap and it only needs to be done once.

**Comment by kraileth** [comment]
@hoper-a11y Please have a look at the "miniraven" repo that I pointed you to. It basically automates the first few steps (building fake-uname for the respective platform, providing a patched bmake to work with it as well as all the dependencies for ravensw (C version)). You might want to run it on an amd64 FreeBSD test machine because that's where it works best so far (there's a strange cmake problem with DragonFly and some FreeBSD i386 problems, too). What's missing then is building ravenadm (which requires Ada).

Miniraven will give you an idea of what platform bring-up is like. It's written in Python and if you don't understand something that it's doing, feel free to ask. I definitely want to provide useful documentation at some point so questions are actually appreciated.

**Comment by hoper-a11y** [comment]
> because it takes an expert to bootstrap and it only needs to be done once.

I just tried to compile ravensw on linux and failed. I know why it needs an expert to bootstrap. No no not because of the Ada stuffs. Ada build environment is well defined and I could set it up on Linux without any problems. We are not even need Ada since we are building the C version of ravensw! The fact is it's (unnecessary) complicated is because it was designed in a way not portable at all (it's reasonable since it's the freebsd's package manager, but on their official github repo they said their code can also be compiled on linux/netbsd/edgebsd, openbsd was removed because no one test it anymore, so they really claimed it to be portable, which is obviously wrong). It build system also stupid (don't want to insult anyone but I have to said so after I checked all of the autosetup stuff). Why don't just simply use automake and autoconf? Only because they are GPLed software? They used the stupid autosetup, that pos can't even check that I already have libarchive and it development headers installed and always said it can't found libarchive!

Sorry for the wall of text. I think I already lost patient with that pkg sh*t and only want to concentrate on building for illumos now.

**Comment by hoper-a11y** [comment]
> @hoper-a11y Please have a look at the "miniraven" repo that I pointed you to. It basically automates the first few steps (building fake-uname for the respective platform, providing a patched bmake to work with it as well as all the dependencies for ravensw (C version)). You might want to run it on an amd64 FreeBSD test machine because that's where it works best so far (there's a strange cmake problem with DragonFly and some FreeBSD i386 problems, too). What's missing then is building ravenadm (which requires Ada).
> 
> Miniraven will give you an idea of what platform bring-up is like. It's written in Python and if you don't understand something that it's doing, feel free to ask. I definitely want to provide useful documentation at some point so questions are actually appreciated.

Unfortunately I read your comment too late. I'm already tired and gave up building the bootstrap archive myself. I will concentrate on the sun platform only. Since pkg (ravensw C version) worked pretty well on this platform, I'm OK with it.

BTW, I read your repo's readme, it seemed miniraven only works on FreeBSD amd64, which is obviously not what I need, since I want to build the raven bootstrap archive on Linux. I would rather have you giving me a list of what needed to setup and I will set everything up myself instead of reading the entire source code of miniraven! Impatient is one of my biggest weaknesses.

**Comment by kraileth** [comment]
@hoper-a11y Heh, patience is indeed a very useful thing to have. But we're all just the way we are. :wink:

Alright, I've just started moving data off one of my machines and plan to install Linux on there (Debian 10 would be most useful for you, I guess?). Then I can give extending Miniraven to make it work with Linux a try. Had some other plans originally, but this might be a good reason to finally look at Linux again (which I've put off for probably too long now).

**Comment by hoper-a11y** [comment]
When will you update the bootstrap for SunOS and Linux? I'm still waiting.

**Comment by hoper-a11y** [comment]
I will close this very misleading titled issue since we all agreed with each other that bootstrapping ravenports/ravensw from source is not needed.
