### ISSUE TITLE
Checking integrity... Segmentation fault on DFBSD

### ISSUE THREAD

**Issue by ghost** [jrmarino/ravensw#6]
> doas /raven/sbin/ravensw install libtool-single-standard
> Updating Raven repository catalog...
> Raven repository is up to date.
> All repositories are up to date.
> The following 1 package(s) will be affected (of 0 checked):
> 
> New packages to be INSTALLED:
> 	libtool-single-standard: 2.4.6
> 
> Number of packages to be installed: 1
> 
> The process will require 2 MiB more space.
> 329 KiB to be downloaded.
> 
> Proceed with this action? [y/N]: y
> [1/1] Fetching libtool-single-standard-2.4.6.tzst: 100%                                 336589 B  67.3kB/s    00:05    
> Checking integrity...Child process pid=3375 terminated abnormally: Segmentation fault

> doas /raven/sbin/ravensw install m4-complete-standard
> Updating Raven repository catalog...
> Raven repository is up to date.
> All repositories are up to date.
> The following 3 package(s) will be affected (of 0 checked):
> 
> New packages to be INSTALLED:
> 	m4-complete-standard: 1.4.18_1
> 	m4-examples-standard: 1.4.18_1
> 	m4-primary-standard: 1.4.18_1
> 
> Number of packages to be installed: 3
> 
> 242 KiB to be downloaded.
> 
> Proceed with this action? [y/N]: y
> [1/3] Fetching m4-complete-standard-1.4.18_1.tzst: 100%                                    458 B   0.5kB/s    00:01    
> [2/3] Fetching m4-examples-standard-1.4.18_1.tzst: 100%                                   7707 B   7.7kB/s    00:01    
> [3/3] Fetching m4-primary-standard-1.4.18_1.tzst: 100%                                 240052 B  80.0kB/s    00:03    
> Checking integrity...Child process pid=3711 terminated abnormally: Segmentation fault

> doas /raven/sbin/ravensw install m4-complete-standard
> Updating Raven repository catalog...
> Raven repository is up to date.
> All repositories are up to date.
> Checking integrity...Child process pid=3845 terminated abnormally: Segmentation fault

**Comment by jrmarino** [comment]
This should be fixed now.
