### ISSUE TITLE
Bootstrap issue - netbsd

### ISSUE THREAD

**Issue by martintc** [jrmarino/ravensw#8]
Setting up ravensw on NetBSD on another machine of mine. When going through the quickstart netbsd guide, I hit an issue at step 2 where it instructs to run command `/raven/sbin/ravensw upgrade`. I get an error stating 

`No signature found in the repository. Can not validate against /raven/etc/ravensw/keys/ravenports.key.key/`

`Unable to update repository Raven`

`Error updating repositories!`

**Comment by jrmarino** [comment]
The repository was signed a long time ago.
